use std::collections::{BTreeMap, BTreeSet};
use std::env;
use std::fmt::Write as _;
use std::fs;
use std::path::{Path, PathBuf};
use std::process::ExitCode;

const GENERATED_HEADER: &str = "// @generated by design-token-codegen; do not edit.\n\
// Source: pocketforge-os/design@999b5c991ee407b491bd279e1d3f68a8001c7f41\n\
#![allow(dead_code)]\n\n";

fn main() -> ExitCode {
    match run() {
        Ok(()) => ExitCode::SUCCESS,
        Err(message) => {
            eprintln!("design-token-codegen: {message}");
            ExitCode::FAILURE
        }
    }
}

fn run() -> Result<(), String> {
    let check = env::args().skip(1).any(|arg| arg == "--check");
    let root = PathBuf::from(env!("CARGO_MANIFEST_DIR")).join("../..");
    let design = root.join("crates/pf-shell-core/design");
    let generated = root.join("crates/pf-shell-core/src/design_generated.rs");
    let inventory = root.join("docs/taffy-property-inventory.md");
    let output = generate(&design)?;
    let inventory_output = generate_inventory(&design)?;
    let counts = inventory_counts(&inventory_output);
    if check {
        let current = fs::read_to_string(&generated)
            .map_err(|error| format!("read {}: {error}", generated.display()))?;
        if current != output {
            return Err(format!(
                "{} is stale; run `cargo run -p design-token-codegen`",
                generated.display()
            ));
        }
        let current = fs::read_to_string(&inventory)
            .map_err(|error| format!("read {}: {error}", inventory.display()))?;
        if current != inventory_output {
            return Err(format!(
                "{} is stale; run `cargo run -p design-token-codegen`",
                inventory.display()
            ));
        }
    } else {
        fs::write(&generated, output)
            .map_err(|error| format!("write {}: {error}", generated.display()))?;
        fs::write(&inventory, inventory_output)
            .map_err(|error| format!("write {}: {error}", inventory.display()))?;
    }
    println!(
        "design inventory dispositions: taffy-supported={} adapter={} prohibited={}",
        counts[0], counts[1], counts[2]
    );
    Ok(())
}

fn inventory_counts(output: &str) -> [usize; 3] {
    ["taffy-supported", "adapter", "prohibited"]
        .map(|value| output.matches(&format!("| {value} |")).count())
}

fn generate_inventory(design: &Path) -> Result<String, String> {
    let mut selectors = BTreeSet::new();
    let mut pseudos = BTreeSet::new();
    let mut media = BTreeSet::new();
    let mut custom = BTreeSet::new();
    let mut properties = BTreeSet::new();
    for file in ["tokens.css", "shell.css"] {
        let css = strip_comments(&read(&design.join(file))?);
        let mut context = Vec::new();
        let mut start = 0;
        for (index, character) in css.char_indices() {
            match character {
                '{' => {
                    let header = css[start..index].trim();
                    context.push(header.to_owned());
                    if header.starts_with("@media ") {
                        media.insert(header.to_owned());
                    } else if !header.starts_with("@font-face") {
                        for selector in header.split(',').map(str::trim).filter(|v| !v.is_empty()) {
                            selectors.insert(selector.to_owned());
                            for pseudo in extract_pseudos(selector) {
                                pseudos.insert(pseudo.to_owned());
                            }
                        }
                    }
                    start = index + 1;
                }
                ';' | '}' => {
                    if let Some((name, _)) = css[start..index].split_once(':') {
                        let name = name.trim();
                        if name.starts_with("--") {
                            custom.insert(name.to_owned());
                        } else if name.chars().all(|c| c.is_ascii_alphanumeric() || c == '-')
                            && !name.is_empty()
                        {
                            properties.insert(name.to_owned());
                        }
                    }
                    if character == '}' {
                        context.pop();
                    }
                    start = index + 1;
                }
                _ => {}
            }
        }
    }
    let mut out = String::from(
        "<!-- @generated by design-token-codegen; do not edit. -->\n# Taffy property inventory\n\nFrozen source: `pocketforge-os/design@999b5c991ee407b491bd279e1d3f68a8001c7f41`. Every construct parsed from the vendored CSS is classified below; `--check` fails if this file is stale or a property has no policy. `taffy-supported` means native layout input, `adapter` means shell translation/paint semantics, and `prohibited` means it must not enter the Taffy style model.\n\n",
    );
    inventory_table(&mut out, "Selectors", selectors, |_| Some("adapter"))?;
    inventory_table(
        &mut out,
        "Pseudo-classes and pseudo-elements",
        pseudos,
        |v| {
            Some(if v.starts_with(":has") || v.starts_with("::-webkit") {
                "prohibited"
            } else {
                "adapter"
            })
        },
    )?;
    inventory_table(&mut out, "Media queries", media, |_| Some("adapter"))?;
    inventory_table(&mut out, "Custom properties", custom, |_| Some("adapter"))?;
    inventory_table(
        &mut out,
        "Layout and paint properties",
        properties,
        property_disposition,
    )?;
    Ok(out)
}

fn extract_pseudos(selector: &str) -> Vec<&str> {
    let bytes = selector.as_bytes();
    let mut result = Vec::new();
    let mut index = 0;
    let mut attribute_depth: usize = 0;
    let mut quote = None;

    while index < bytes.len() {
        let byte = bytes[index];
        if let Some(delimiter) = quote {
            if byte == b'\\' {
                index = (index + 2).min(bytes.len());
                continue;
            }
            if byte == delimiter {
                quote = None;
            }
            index += 1;
            continue;
        }
        match byte {
            b'\'' | b'"' => quote = Some(byte),
            b'[' => attribute_depth += 1,
            b']' => attribute_depth = attribute_depth.saturating_sub(1),
            b':' if attribute_depth == 0 => {
                let start = index;
                index += 1;
                if bytes.get(index) == Some(&b':') {
                    index += 1;
                }
                while bytes
                    .get(index)
                    .is_some_and(|byte| byte.is_ascii_alphanumeric() || matches!(byte, b'-' | b'_'))
                {
                    index += 1;
                }
                if bytes.get(index) == Some(&b'(') {
                    index = balanced_parenthesized_end(bytes, index);
                }
                result.push(&selector[start..index]);
                continue;
            }
            _ => {}
        }
        index += 1;
    }
    result
}

fn balanced_parenthesized_end(bytes: &[u8], mut index: usize) -> usize {
    let mut depth = 0;
    let mut quote = None;
    while index < bytes.len() {
        let byte = bytes[index];
        if let Some(delimiter) = quote {
            if byte == b'\\' {
                index = (index + 2).min(bytes.len());
                continue;
            }
            if byte == delimiter {
                quote = None;
            }
        } else {
            match byte {
                b'\'' | b'"' => quote = Some(byte),
                b'(' => depth += 1,
                b')' => {
                    depth -= 1;
                    if depth == 0 {
                        return index + 1;
                    }
                }
                _ => {}
            }
        }
        index += 1;
    }
    index
}

fn inventory_table<F>(
    out: &mut String,
    heading: &str,
    values: BTreeSet<String>,
    classify: F,
) -> Result<(), String>
where
    F: Fn(&str) -> Option<&'static str>,
{
    writeln!(
        out,
        "## {heading}\n\n| Construct | Disposition |\n|---|---|"
    )
    .unwrap();
    for value in values {
        let disposition =
            classify(&value).ok_or_else(|| format!("unclassified CSS construct {value:?}"))?;
        writeln!(out, "| `{}` | {disposition} |", value.replace('|', "\\|")).unwrap();
    }
    out.push('\n');
    Ok(())
}

fn property_disposition(name: &str) -> Option<&'static str> {
    const TAFFY: &[&str] = &[
        "align-items",
        "bottom",
        "box-sizing",
        "display",
        "flex",
        "flex-direction",
        "gap",
        "grid-template-columns",
        "height",
        "inset",
        "justify-content",
        "left",
        "margin",
        "margin-bottom",
        "margin-left",
        "margin-right",
        "margin-top",
        "max-width",
        "min-height",
        "min-width",
        "overflow",
        "overflow-y",
        "padding",
        "padding-bottom",
        "padding-top",
        "position",
        "right",
        "top",
        "width",
    ];
    const PROHIBITED: &[&str] = &[
        "-webkit-font-smoothing",
        "-webkit-mask",
        "mask",
        "scroll-behavior",
        "scroll-padding",
        "scroll-padding-top",
        "scrollbar-width",
    ];
    const ADAPTER: &[&str] = &[
        "background",
        "border",
        "border-color",
        "border-left",
        "border-radius",
        "border-style",
        "border-top",
        "box-shadow",
        "color",
        "content",
        "font-display",
        "font-family",
        "font-size",
        "font-style",
        "font-weight",
        "letter-spacing",
        "line-height",
        "object-fit",
        "opacity",
        "pointer-events",
        "src",
        "text-overflow",
        "text-transform",
        "transform",
        "transition",
        "vertical-align",
        "white-space",
        "z-index",
    ];
    if TAFFY.contains(&name) {
        Some("taffy-supported")
    } else if PROHIBITED.contains(&name) {
        Some("prohibited")
    } else if ADAPTER.contains(&name) {
        Some("adapter")
    } else {
        None
    }
}

fn generate(design: &Path) -> Result<String, String> {
    let tokens = read(&design.join("tokens.css"))?;
    let shell = read(&design.join("shell.css"))?;
    let declarations = declarations(&tokens);
    let mut names = BTreeSet::new();
    for name in declarations.keys() {
        if ["--radius-", "--space-", "--type-", "--color-", "--state-"]
            .iter()
            .any(|prefix| name.starts_with(prefix))
        {
            names.insert(name.as_str());
        }
    }

    let mut output = String::from(GENERATED_HEADER);
    for name in names {
        let value = declarations
            .get(name)
            .expect("name came from declarations map");
        let ident = rust_ident(name);
        writeln!(
            output,
            "pub const {ident}_TOKEN: &str = {};",
            rust_string(name)
        )
        .expect("writing to a String cannot fail");
        writeln!(
            output,
            "pub const {ident}_CSS: &str = {};",
            rust_string(value)
        )
        .expect("writing to a String cannot fail");
        if let Some(number) = css_number(value) {
            writeln!(output, "pub const {ident}: f32 = {number};")
                .expect("writing to a String cannot fail");
        }
    }

    output.push_str("\n// Mechanically extracted component values from shell.css.\n");
    chrome_components(&mut output, &shell, &declarations)?;
    component(
        &mut output,
        &shell,
        ".promptbar",
        "height",
        "PROMPTS_AREA_HEIGHT",
    )?;
    component(&mut output, &shell, ".lib-head", "top", "LIB_HEAD_TOP")?;
    component(
        &mut output,
        &shell,
        ".searchbox",
        "height",
        "LIB_TOOLBAR_HEIGHT",
    )?;
    component(&mut output, &shell, ".lib-grid", "top", "LIB_GRID_TOP")?;
    component(
        &mut output,
        &shell,
        ".lib-grid .card .art",
        "height",
        "LIB_CARD_ART_HEIGHT",
    )?;
    component(&mut output, &shell, ".card", "width", "CARD_ART_WIDTH")?;
    component(
        &mut output,
        &shell,
        ".card .art",
        "height",
        "CARD_ART_HEIGHT",
    )?;
    component(&mut output, &shell, ".chip", "height", "CHIP_HEIGHT")?;
    component_border_width(&mut output, &shell, ".chip", "border", "CHIP_BORDER_WIDTH")?;
    component_padding(
        &mut output,
        &shell,
        &declarations,
        ".chip",
        "CHIP_HORIZONTAL_PADDING",
    )?;
    component_border_width(
        &mut output,
        &shell,
        ".seg .opt + .opt",
        "border-left",
        "SEGMENT_DIVIDER_WIDTH",
    )?;
    output.push_str("pub const CARD_ART_ASPECT: f32 = CARD_ART_WIDTH / CARD_ART_HEIGHT;\n");
    Ok(output)
}

fn chrome_components(
    output: &mut String,
    shell: &str,
    declarations: &BTreeMap<String, String>,
) -> Result<(), String> {
    component(output, shell, ".statusbar", "height", "STATUS_BAR_HEIGHT")?;
    component_padding(
        output,
        shell,
        declarations,
        ".statusbar",
        "STATUS_BAR_HORIZONTAL_PADDING",
    )?;
    component(
        output,
        shell,
        ".statusbar-side",
        "width",
        "STATUS_BAR_SIDE_WIDTH",
    )?;
    component_resolved(
        output,
        shell,
        declarations,
        ".rooms",
        "gap",
        "ROOM_STRIP_GAP",
    )?;
    component_padding(
        output,
        shell,
        declarations,
        ".room",
        "ROOM_HORIZONTAL_PADDING",
    )?;
    component(output, shell, "\n.keycap", "height", "KEYCAP_HEIGHT")?;
    component(output, shell, "\n.keycap", "min-width", "KEYCAP_MIN_WIDTH")?;
    component_border_width(output, shell, "\n.keycap", "border", "KEYCAP_BORDER_WIDTH")
}

fn read(path: &Path) -> Result<String, String> {
    fs::read_to_string(path).map_err(|error| format!("read {}: {error}", path.display()))
}

fn declarations(css: &str) -> BTreeMap<String, String> {
    let clean = strip_comments(css);
    let mut result = BTreeMap::new();
    for declaration in clean.split([';', '{', '}']) {
        if let Some((name, value)) = declaration.split_once(':') {
            let name = name.trim();
            if name.starts_with("--") {
                result
                    .entry(name.to_owned())
                    .or_insert_with(|| value.trim().to_owned());
            }
        }
    }
    result
}

fn strip_comments(input: &str) -> String {
    let mut output = String::with_capacity(input.len());
    let mut rest = input;
    while let Some(start) = rest.find("/*") {
        output.push_str(&rest[..start]);
        let after = &rest[start + 2..];
        rest = after.find("*/").map_or("", |end| &after[end + 2..]);
    }
    output.push_str(rest);
    output
}

fn rust_ident(name: &str) -> String {
    name.trim_start_matches("--")
        .chars()
        .map(|character| {
            if character.is_ascii_alphanumeric() {
                character.to_ascii_uppercase()
            } else {
                '_'
            }
        })
        .collect()
}

fn rust_string(value: &str) -> String {
    format!("{value:?}")
}

fn css_number(value: &str) -> Option<String> {
    let (raw, factor) = if let Some(raw) = value.strip_suffix("px") {
        (raw, 1.0)
    } else if let Some(raw) = value.strip_suffix("rem") {
        (raw, 16.0)
    } else if let Some(raw) = value.strip_suffix("em") {
        (raw, 1.0)
    } else if value.parse::<f32>().is_ok() {
        (value, 1.0)
    } else {
        return None;
    };
    let parsed = raw.trim().parse::<f32>().ok()? * factor;
    Some(format!("{parsed:?}"))
}

fn rule(css: &str, selector: &str) -> Result<String, String> {
    let clean = strip_comments(css);
    let marker = format!("{selector} {{");
    let start = clean
        .find(&marker)
        .ok_or_else(|| format!("selector {selector:?} not found in shell.css"))?
        + marker.len();
    let end = clean[start..]
        .find('}')
        .ok_or_else(|| format!("selector {selector:?} has no closing brace"))?
        + start;
    Ok(clean[start..end].to_owned())
}

fn property(css: &str, selector: &str, property: &str) -> Result<String, String> {
    for declaration in rule(css, selector)?.split(';') {
        if let Some((name, value)) = declaration.split_once(':') {
            if name.trim() == property {
                return Ok(value.trim().to_owned());
            }
        }
    }
    Err(format!(
        "property {property:?} missing from selector {selector:?}"
    ))
}

fn component(
    output: &mut String,
    css: &str,
    selector: &str,
    property_name: &str,
    ident: &str,
) -> Result<(), String> {
    let value = property(css, selector, property_name)?;
    let number = css_number(&value).ok_or_else(|| {
        format!("{selector} {property_name} value {value:?} is not a simple CSS dimension")
    })?;
    writeln!(output, "pub const {ident}: f32 = {number};")
        .expect("writing to a String cannot fail");
    Ok(())
}

fn component_resolved(
    output: &mut String,
    css: &str,
    tokens: &BTreeMap<String, String>,
    selector: &str,
    property_name: &str,
    ident: &str,
) -> Result<(), String> {
    let value = property(css, selector, property_name)?;
    let variable = value
        .strip_prefix("var(")
        .and_then(|value| value.strip_suffix(')'))
        .unwrap_or(&value);
    let resolved = tokens.get(variable).map_or(value.as_str(), String::as_str);
    let number = css_number(resolved).ok_or_else(|| {
        format!("{selector} {property_name} value {value:?} is not a simple CSS dimension")
    })?;
    writeln!(output, "pub const {ident}: f32 = {number};")
        .expect("writing to a String cannot fail");
    Ok(())
}

fn component_padding(
    output: &mut String,
    css: &str,
    tokens: &BTreeMap<String, String>,
    selector: &str,
    ident: &str,
) -> Result<(), String> {
    let value = property(css, selector, "padding")?;
    let horizontal = value
        .split_whitespace()
        .nth(1)
        .ok_or_else(|| format!("{selector} padding must have vertical and horizontal values"))?;
    let variable = horizontal
        .strip_prefix("var(")
        .and_then(|value| value.strip_suffix(')'))
        .unwrap_or(horizontal);
    let resolved = tokens.get(variable).map_or(horizontal, String::as_str);
    let number = css_number(resolved)
        .ok_or_else(|| format!("{selector} horizontal padding {horizontal:?} is not numeric"))?;
    writeln!(output, "pub const {ident}: f32 = {number};")
        .expect("writing to a String cannot fail");
    Ok(())
}

fn component_border_width(
    output: &mut String,
    css: &str,
    selector: &str,
    property_name: &str,
    ident: &str,
) -> Result<(), String> {
    let value = property(css, selector, property_name)?;
    let width = value
        .split_whitespace()
        .next()
        .ok_or_else(|| format!("{selector} {property_name} is empty"))?;
    let number = css_number(width)
        .ok_or_else(|| format!("{selector} {property_name} width {width:?} is not numeric"))?;
    writeln!(output, "pub const {ident}: f32 = {number};")
        .expect("writing to a String cannot fail");
    Ok(())
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn parses_pseudo_element_once() {
        assert_eq!(extract_pseudos(".focusable::after"), ["::after"]);
    }

    #[test]
    fn parses_vendor_prefixed_pseudo_element_once() {
        assert_eq!(
            extract_pseudos(".lib-grid::-webkit-scrollbar"),
            ["::-webkit-scrollbar"]
        );
    }

    #[test]
    fn parses_functional_pseudo_class_as_one_complete_construct() {
        assert_eq!(
            extract_pseudos(".card:has(.art[data-focused=\"true\"]) .label"),
            [":has(.art[data-focused=\"true\"])"],
        );
    }

    #[test]
    fn parses_all_required_token_families() {
        let root = PathBuf::from(env!("CARGO_MANIFEST_DIR")).join("../..");
        let generated = generate(&root.join("crates/pf-shell-core/design")).unwrap();
        for expected in [
            "RADIUS_S",
            "RADIUS_M",
            "RADIUS_L",
            "RADIUS_PILL",
            "SPACE_1",
            "SPACE_8",
            "TYPE_HERO_SIZE",
            "TYPE_EYEBROW_TRACKING",
            "COLOR_SURFACE_CANVAS_CSS",
            "STATE_REST_SURFACE_CSS",
            "STATE_UNAVAILABLE_VEIL_CSS",
        ] {
            assert!(
                generated.contains(&format!("pub const {expected}")),
                "missing {expected}"
            );
        }
    }

    #[test]
    fn shell_emission_does_not_hand_copy_generated_tokens_or_dimensions() {
        let root = PathBuf::from(env!("CARGO_MANIFEST_DIR")).join("../..");
        let source = read(&root.join("crates/pf-shell-core/src/lib.rs")).unwrap();
        for (line_number, line) in source.lines().enumerate() {
            if line.contains("\"--color-transparent\"") {
                continue;
            }
            assert!(
                ![
                    "\"--radius-",
                    "\"--space-",
                    "\"--type-",
                    "\"--color-",
                    "\"--state-"
                ]
                .iter()
                .any(|prefix| line.contains(prefix)),
                "hard-coded design token at lib.rs:{}: {line}",
                line_number + 1
            );
        }
        for forbidden in [
            "const STATUS_BAR_HEIGHT:",
            "const PROMPTS_AREA_HEIGHT:",
            "const LIB_HEAD_TOP:",
            "const LIB_TOOLBAR_HEIGHT:",
            "const LIB_GRID_TOP:",
            "const LIB_CARD_ART_HEIGHT:",
            "const CARD_ART_WIDTH:",
            "const CARD_ART_HEIGHT:",
            "const CHIP_HORIZONTAL_PADDING:",
            "let chip_height = 36.0",
            "let chip_height = 44.0",
            "const RADIUS_S:",
            "const RADIUS_M:",
            "const RADIUS_L:",
            "const RADIUS_PILL:",
        ] {
            assert!(
                !source.contains(forbidden),
                "hard-coded CSS dimension escaped generated/manual modules: {forbidden}"
            );
        }
    }
}
