use std::collections::{BTreeMap, BTreeSet};
use std::env;
use std::fmt::Write as _;
use std::fs;
use std::path::{Path, PathBuf};
use std::process::ExitCode;

const GENERATED_HEADER: &str = "// @generated by design-token-codegen; do not edit.\n\
// Source: pocketforge-os/design@999b5c991ee407b491bd279e1d3f68a8001c7f41\n\
#![allow(dead_code)]\n\n";

fn main() -> ExitCode {
    match run() {
        Ok(()) => ExitCode::SUCCESS,
        Err(message) => {
            eprintln!("design-token-codegen: {message}");
            ExitCode::FAILURE
        }
    }
}

fn run() -> Result<(), String> {
    let check = env::args().skip(1).any(|arg| arg == "--check");
    let root = PathBuf::from(env!("CARGO_MANIFEST_DIR")).join("../..");
    let design = root.join("crates/pf-shell-core/design");
    let generated = root.join("crates/pf-shell-core/src/design_generated.rs");
    let output = generate(&design)?;
    if check {
        let current = fs::read_to_string(&generated)
            .map_err(|error| format!("read {}: {error}", generated.display()))?;
        if current != output {
            return Err(format!(
                "{} is stale; run `cargo run -p design-token-codegen`",
                generated.display()
            ));
        }
    } else {
        fs::write(&generated, output)
            .map_err(|error| format!("write {}: {error}", generated.display()))?;
    }
    Ok(())
}

fn generate(design: &Path) -> Result<String, String> {
    let tokens = read(&design.join("tokens.css"))?;
    let shell = read(&design.join("shell.css"))?;
    let declarations = declarations(&tokens);
    let mut names = BTreeSet::new();
    for name in declarations.keys() {
        if ["--radius-", "--space-", "--type-", "--color-", "--state-"]
            .iter()
            .any(|prefix| name.starts_with(prefix))
        {
            names.insert(name.as_str());
        }
    }

    let mut output = String::from(GENERATED_HEADER);
    for name in names {
        let value = declarations
            .get(name)
            .expect("name came from declarations map");
        let ident = rust_ident(name);
        writeln!(
            output,
            "pub const {ident}_TOKEN: &str = {};",
            rust_string(name)
        )
        .expect("writing to a String cannot fail");
        writeln!(
            output,
            "pub const {ident}_CSS: &str = {};",
            rust_string(value)
        )
        .expect("writing to a String cannot fail");
        if let Some(number) = css_number(value) {
            writeln!(output, "pub const {ident}: f32 = {number};")
                .expect("writing to a String cannot fail");
        }
    }

    output.push_str("\n// Mechanically extracted component values from shell.css.\n");
    component(
        &mut output,
        &shell,
        ".statusbar",
        "height",
        "STATUS_BAR_HEIGHT",
    )?;
    component(
        &mut output,
        &shell,
        ".promptbar",
        "height",
        "PROMPTS_AREA_HEIGHT",
    )?;
    component(&mut output, &shell, ".card", "width", "CARD_ART_WIDTH")?;
    component(
        &mut output,
        &shell,
        ".card .art",
        "height",
        "CARD_ART_HEIGHT",
    )?;
    component(&mut output, &shell, ".chip", "height", "CHIP_HEIGHT")?;
    component_padding(
        &mut output,
        &shell,
        &declarations,
        ".chip",
        "CHIP_HORIZONTAL_PADDING",
    )?;
    component_border_width(
        &mut output,
        &shell,
        ".seg .opt + .opt",
        "border-left",
        "SEGMENT_DIVIDER_WIDTH",
    )?;
    output.push_str("pub const CARD_ART_ASPECT: f32 = CARD_ART_WIDTH / CARD_ART_HEIGHT;\n");
    Ok(output)
}

fn read(path: &Path) -> Result<String, String> {
    fs::read_to_string(path).map_err(|error| format!("read {}: {error}", path.display()))
}

fn declarations(css: &str) -> BTreeMap<String, String> {
    let clean = strip_comments(css);
    let mut result = BTreeMap::new();
    for declaration in clean.split([';', '{', '}']) {
        if let Some((name, value)) = declaration.split_once(':') {
            let name = name.trim();
            if name.starts_with("--") {
                result
                    .entry(name.to_owned())
                    .or_insert_with(|| value.trim().to_owned());
            }
        }
    }
    result
}

fn strip_comments(input: &str) -> String {
    let mut output = String::with_capacity(input.len());
    let mut rest = input;
    while let Some(start) = rest.find("/*") {
        output.push_str(&rest[..start]);
        let after = &rest[start + 2..];
        rest = after.find("*/").map_or("", |end| &after[end + 2..]);
    }
    output.push_str(rest);
    output
}

fn rust_ident(name: &str) -> String {
    name.trim_start_matches("--")
        .chars()
        .map(|character| {
            if character.is_ascii_alphanumeric() {
                character.to_ascii_uppercase()
            } else {
                '_'
            }
        })
        .collect()
}

fn rust_string(value: &str) -> String {
    format!("{value:?}")
}

fn css_number(value: &str) -> Option<String> {
    let (raw, factor) = if let Some(raw) = value.strip_suffix("px") {
        (raw, 1.0)
    } else if let Some(raw) = value.strip_suffix("rem") {
        (raw, 16.0)
    } else if let Some(raw) = value.strip_suffix("em") {
        (raw, 1.0)
    } else if value.parse::<f32>().is_ok() {
        (value, 1.0)
    } else {
        return None;
    };
    let parsed = raw.trim().parse::<f32>().ok()? * factor;
    Some(format!("{parsed:?}"))
}

fn rule(css: &str, selector: &str) -> Result<String, String> {
    let clean = strip_comments(css);
    let marker = format!("{selector} {{");
    let start = clean
        .find(&marker)
        .ok_or_else(|| format!("selector {selector:?} not found in shell.css"))?
        + marker.len();
    let end = clean[start..]
        .find('}')
        .ok_or_else(|| format!("selector {selector:?} has no closing brace"))?
        + start;
    Ok(clean[start..end].to_owned())
}

fn property(css: &str, selector: &str, property: &str) -> Result<String, String> {
    for declaration in rule(css, selector)?.split(';') {
        if let Some((name, value)) = declaration.split_once(':') {
            if name.trim() == property {
                return Ok(value.trim().to_owned());
            }
        }
    }
    Err(format!(
        "property {property:?} missing from selector {selector:?}"
    ))
}

fn component(
    output: &mut String,
    css: &str,
    selector: &str,
    property_name: &str,
    ident: &str,
) -> Result<(), String> {
    let value = property(css, selector, property_name)?;
    let number = css_number(&value).ok_or_else(|| {
        format!("{selector} {property_name} value {value:?} is not a simple CSS dimension")
    })?;
    writeln!(output, "pub const {ident}: f32 = {number};")
        .expect("writing to a String cannot fail");
    Ok(())
}

fn component_padding(
    output: &mut String,
    css: &str,
    tokens: &BTreeMap<String, String>,
    selector: &str,
    ident: &str,
) -> Result<(), String> {
    let value = property(css, selector, "padding")?;
    let horizontal = value
        .split_whitespace()
        .nth(1)
        .ok_or_else(|| format!("{selector} padding must have vertical and horizontal values"))?;
    let variable = horizontal
        .strip_prefix("var(")
        .and_then(|value| value.strip_suffix(')'))
        .unwrap_or(horizontal);
    let resolved = tokens.get(variable).map_or(horizontal, String::as_str);
    let number = css_number(resolved)
        .ok_or_else(|| format!("{selector} horizontal padding {horizontal:?} is not numeric"))?;
    writeln!(output, "pub const {ident}: f32 = {number};")
        .expect("writing to a String cannot fail");
    Ok(())
}

fn component_border_width(
    output: &mut String,
    css: &str,
    selector: &str,
    property_name: &str,
    ident: &str,
) -> Result<(), String> {
    let value = property(css, selector, property_name)?;
    let width = value
        .split_whitespace()
        .next()
        .ok_or_else(|| format!("{selector} {property_name} is empty"))?;
    let number = css_number(width)
        .ok_or_else(|| format!("{selector} {property_name} width {width:?} is not numeric"))?;
    writeln!(output, "pub const {ident}: f32 = {number};")
        .expect("writing to a String cannot fail");
    Ok(())
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn parses_all_required_token_families() {
        let root = PathBuf::from(env!("CARGO_MANIFEST_DIR")).join("../..");
        let generated = generate(&root.join("crates/pf-shell-core/design")).unwrap();
        for expected in [
            "RADIUS_S",
            "RADIUS_M",
            "RADIUS_L",
            "RADIUS_PILL",
            "SPACE_1",
            "SPACE_8",
            "TYPE_HERO_SIZE",
            "TYPE_EYEBROW_TRACKING",
            "COLOR_SURFACE_CANVAS_CSS",
            "STATE_REST_SURFACE_CSS",
            "STATE_UNAVAILABLE_VEIL_CSS",
        ] {
            assert!(
                generated.contains(&format!("pub const {expected}")),
                "missing {expected}"
            );
        }
    }

    #[test]
    fn shell_emission_does_not_hand_copy_generated_tokens_or_dimensions() {
        let root = PathBuf::from(env!("CARGO_MANIFEST_DIR")).join("../..");
        let source = read(&root.join("crates/pf-shell-core/src/lib.rs")).unwrap();
        for (line_number, line) in source.lines().enumerate() {
            if line.contains("\"--color-transparent\"") {
                continue;
            }
            assert!(
                ![
                    "\"--radius-",
                    "\"--space-",
                    "\"--type-",
                    "\"--color-",
                    "\"--state-"
                ]
                .iter()
                .any(|prefix| line.contains(prefix)),
                "hard-coded design token at lib.rs:{}: {line}",
                line_number + 1
            );
        }
        for forbidden in [
            "const STATUS_BAR_HEIGHT:",
            "const PROMPTS_AREA_HEIGHT:",
            "const CARD_ART_WIDTH:",
            "const CARD_ART_HEIGHT:",
            "const CHIP_HORIZONTAL_PADDING:",
            "let chip_height = 36.0",
            "let chip_height = 44.0",
            "const RADIUS_S:",
            "const RADIUS_M:",
            "const RADIUS_L:",
            "const RADIUS_PILL:",
        ] {
            assert!(
                !source.contains(forbidden),
                "hard-coded CSS dimension escaped generated/manual modules: {forbidden}"
            );
        }
    }
}
