[source.crates-io]
replace-with = "vendored-sources"

[source."git+https://github.com/pocketforge-os/runtime.git?rev=b5b6559b354ed6ddf033141f867c8ff74b650409"]
git = "https://github.com/pocketforge-os/runtime.git"
rev = "b5b6559b354ed6ddf033141f867c8ff74b650409"
replace-with = "vendored-sources"

[source.vendored-sources]
directory = "vendor"

[net]
offline = true
